config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :user_profiles

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]

  #->Prelang (user_login/devise)
  has_one :user_profile
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    # The User was found in our database
    return user if user

    # Check if the User is already registered without Facebook
    user = User.where(email: auth.info.email).first

    return user if user

    # The User was not found and we need to create them
    User.create(name:     auth.extra.raw_info.name,
                provider: auth.provider,
                uid:      auth.uid,
                email:    auth.info.email,
                password: Devise.friendly_token[0,20])
  end


  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user
  validates_formatting_of :email1, using: :email
  validates_formatting_of :email2, using: :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render :show, status: :created, location: @user_profile }
      else
        format.html { render :new }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_profile }
      else
        format.html { render :edit }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url, notice: 'User profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:user_id, :first_name, :middle_name, :surname, :sex, :birthdate, :height, :weight, :smoker, :address1, :address2, :address3, :suburb, :state, :country, :postcode, :email1, :email2, :phone_home, :phone_mob, :profession, :title)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include ApplicationHelper

  def facebook

    # Attempt to find the User
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication # This will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      #session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/landings/index.html.erb
<h1>Landings#index</h1>
<p>Find me in app/views/landings/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoHasslsUserDash</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/><!-- Prelang: Analytics / Google Analytics -->
    <%= analytics_init if Rails.env.production? or Rails.env.development? %></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/user_profiles/_form.html.erb
<%= form_for @user_profile, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :first_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :first_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :middle_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :middle_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :surname, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :surname, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sex, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :sex, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :birthdate, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :birthdate, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :height, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :height, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :weight, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :weight, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :smoker, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :smoker, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address1, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :address1, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address2, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :address2, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address3, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :address3, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :suburb, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :suburb, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :state, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :country, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :country, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :postcode, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :postcode, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email1, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.email_field :email1, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email2, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.email_field :email2, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_home, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :phone_home, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_mob, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :phone_mob, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :profession, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :profession, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  user_profiles_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<%- model_class = UserProfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => UserProfile %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_profiles/index.html.erb
<%- model_class = UserProfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => UserProfile %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:middle_name) %></th>
      <th><%= model_class.human_attribute_name(:surname) %></th>
      <th><%= model_class.human_attribute_name(:sex) %></th>
      <th><%= model_class.human_attribute_name(:birthdate) %></th>
      <th><%= model_class.human_attribute_name(:height) %></th>
      <th><%= model_class.human_attribute_name(:weight) %></th>
      <th><%= model_class.human_attribute_name(:smoker) %></th>
      <th><%= model_class.human_attribute_name(:address1) %></th>
      <th><%= model_class.human_attribute_name(:address2) %></th>
      <th><%= model_class.human_attribute_name(:address3) %></th>
      <th><%= model_class.human_attribute_name(:suburb) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:postcode) %></th>
      <th><%= model_class.human_attribute_name(:email1) %></th>
      <th><%= model_class.human_attribute_name(:email2) %></th>
      <th><%= model_class.human_attribute_name(:phone_home) %></th>
      <th><%= model_class.human_attribute_name(:phone_mob) %></th>
      <th><%= model_class.human_attribute_name(:profession) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.id %></td>
        <td><%= user_profile.first_name %></td>
        <td><%= user_profile.middle_name %></td>
        <td><%= user_profile.surname %></td>
        <td><%= user_profile.sex %></td>
        <td><%= user_profile.birthdate %></td>
        <td><%= user_profile.height %></td>
        <td><%= user_profile.weight %></td>
        <td><%= user_profile.smoker %></td>
        <td><%= user_profile.address1 %></td>
        <td><%= user_profile.address2 %></td>
        <td><%= user_profile.address3 %></td>
        <td><%= user_profile.suburb %></td>
        <td><%= user_profile.state %></td>
        <td><%= user_profile.country %></td>
        <td><%= user_profile.postcode %></td>
        <td><%= user_profile.email1 %></td>
        <td><%= user_profile.email2 %></td>
        <td><%= user_profile.phone_home %></td>
        <td><%= user_profile.phone_mob %></td>
        <td><%= user_profile.profession %></td>
        <td><%= user_profile.title %></td>
        <td><%=l user_profile.created_at, format: :long %></td>
        <td>
          <%= link_to user_profile_path(user_profile), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to user_profile_path(user_profile), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_profile_path,
            :class => 'btn btn-primary' %>

app/views/user_profiles/new.html.erb
<%- model_class = UserProfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => UserProfile %></h1>
</div>
<%= render :partial => 'form' %>

app/views/user_profiles/show.html.erb
<%- model_class = UserProfile -%>
<div class="page-header">
  <h1><%=t '.title', :default => UserProfile %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:first_name) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.first_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:middle_name) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.middle_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:surname) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.surname %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:sex) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.sex %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:birthdate) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.birthdate %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:height) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.height %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:weight) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.weight %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:smoker) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.smoker %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address1) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.address1 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address2) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.address2 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:address3) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.address3 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:suburb) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.suburb %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:state) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.state %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:country) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.country %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:postcode) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.postcode %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:email1) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.email1 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:email2) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.email2 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone_home) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.phone_home %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone_mob) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.phone_mob %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:profession) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.profession %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @user_profile.title %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              user_profiles_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_profile_path(@user_profile), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_profile_path(@user_profile),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>